### ISSUE TITLE
zigbee2mqtt

### ISSUE THREAD

**Issue by gedw99** [barnybug/gohome#6]
saw the zigbee2mqtt call in the mqtt service at https://github.com/barnybug/gohome/blob/master/services/zigbee/main.go

your calling this ? https://www.zigbee2mqtt.io/

Want to try out running a few Ikea mqtt things. And casting to the ikea sonos gear. 

Can you let me know please...

**Comment by barnybug** [comment]
Yes, I'm using zigbee2mqtt with a CC2531 stick.
